# events block obligatoire pour que NGINX accepte la configuration
events {
    worker_connections 1024;
}

http {
    # Inclut la liste des types MIME (comment le navigateur doit lire les CSS, scripts...)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # Écoute UNIQUEMENT sur le port 443 en IPv4 et IPv6 (Le sujet impose 443 only)
        listen 443 ssl;
        listen [::]:443 ssl;

        # C'est ici que tu définis le domaine local
        server_name eel-abed.42.fr;

        # Localisation de la racine du site et du fichier index par défaut
        root /var/www/wordpress;
        index index.php index.html index.htm;

        # Chemins vers nos nouveaux certificats SSL auto-signés
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        
        # Le sujet impose TLSv1.2 ou TLSv1.3 uniquement
        ssl_protocols TLSv1.2 TLSv1.3;

        # Toutes les requêtes HTTP traditionnelles sont redirigées si besoin
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # Demande à NGINX de forwarder tout ce qui se termine par '.php' vers le conteneur WordPress
        location ~ \.php$ {
            # Séparation de l'URL pour passer l'info à FastCGI
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            
            # Le nom du conteneur wordpress sur le port 9000
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}
