version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - credentials.txt
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eel-abed/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eel-abed/data/wordpress

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials.txt:
    file: ../secrets/credentials.txt
