[www]
user = www-data
group = www-data

; On écoute sur le port 9000 sur TOUTES les interfaces (0.0.0.0) au lieu d'un socket unix (local)
listen = 0.0.0.0:9000

listen.owner = www-data
listen.group = www-data

; Très important pour que PHP-FPM ait accès à nos variables d'environnement (.env / secrets)
clear_env = no

; Configuration de la gestion des ressources dynamiques
pm = dynamic
pm.max_children = 25
pm.start_servers = 5
pm.min_spare_servers = 1
pm.max_spare_servers = 10
